using System.Drawing.Imaging;
using System.IO;
using System.Threading.Tasks;

using MediaDeck.Composition.Enum;
using MediaDeck.Database;
using MediaDeck.Database.Tables;
using MediaDeck.MediaItemTypes.Base.Models;

using Microsoft.Extensions.Logging;

using Patagames.Pdf.Enums;
using Patagames.Pdf.Net;

namespace MediaDeck.MediaItemTypes.Pdf.Models;

[Inject(InjectServiceLifetime.Transient)]
internal partial class PdfMediaItemOperator : BaseMediaItemOperator {
	private readonly IFilePathService _filePathService;
	private readonly ILogger<PdfMediaItemOperator> _logger;

	public PdfMediaItemOperator(
		IFilePathService filePathService,
		ILogger<PdfMediaItemOperator> logger,
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.Pdf) {
		this._filePathService = filePathService;
		this._logger = logger;
	}

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaItems.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}

		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath();
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);
		try {
			var image = this.CreateThumbnail(filePath, 300, 300, 1);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch (Exception ex) {
			this._logger.LogError(ex, "Failed to create pdf thumbnail for file {FilePath}", filePath);
			thumbPath = null;
			thumbRelativePath = null;
		}

		var pdfDocument = PdfDocument.Load(filePath);
		var fileInfo = new FileInfo(filePath);

		var mf = new MediaItem {
			ItemType = ItemType.Pdf,
			DirectoryPath = Path.GetDirectoryName(filePath)!,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists,
			Width = (int)pdfDocument.Pages[0].Width,
			Height = (int)pdfDocument.Pages[1].Height,
			Container = new() { PageCount = pdfDocument.Pages.Count }
		};

		await db.MediaItems.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._updateFileHashBackgroundService.EnqueueHashUpdate(mf.MediaItemId);

		return mf;
	}

	/// <summary>
	/// サムネイル作成
	/// </summary>
	/// <param name="filePath">動画ファイルパス</param>
	/// <param name="width">サムネイル幅</param>
	/// <param name="height">サムネイル高さ</param>
	/// <param name="pageNumber">サムネイルにするページ番号</param>
	/// <returns>作成されたサムネイルファイル名</returns>
	internal byte[] CreateThumbnail(string filePath, int width, int height, int pageNumber = 1) {
		var pdfDoc = PdfDocument.Load(filePath);
		var page = pdfDoc.Pages[pageNumber - 1];
		using var pdfBitmap = new PdfBitmap(width, height, true);
		page.Render(pdfBitmap, 0, 0, width, height, PageRotate.Normal, RenderFlags.FPDF_NONE);
		using var ms = new MemoryStream();

		using var image = pdfBitmap.GetImage();
		image.Save(ms, ImageFormat.Jpeg);
		return ms.ToArray();
	}
}