using System.Globalization;
using System.Linq.Expressions;

using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Tables;

namespace MediaDeck.Core.Models.Files.SearchConditions;

/// <summary>
/// <see cref="MediaItem"/> 上で <c>prop.</c> サジェスト・比較対象とできるプロパティのカタログ。
/// 式ツリーは <see cref="SearchTypeConverters.BuildComparisonExpression{TEntity, T}"/>
/// を介してコンパイルされ、EF Core の <c>WHERE</c> 句にも変換可能な形式で返される。
/// </summary>
public static class MediaItemPropertyCatalog {
	private static readonly IReadOnlyList<SearchTypeComparison> AllComparisons = [
		SearchTypeComparison.GreaterThan,
		SearchTypeComparison.GreaterThanOrEqual,
		SearchTypeComparison.Equal,
		SearchTypeComparison.LessThanOrEqual,
		SearchTypeComparison.LessThan,
	];

	private static readonly IReadOnlyList<SearchTypeComparison> EqualityOnly = [SearchTypeComparison.Equal];

	/// <summary>カタログ本体。</summary>
	public static IReadOnlyList<MediaItemPropertyDescriptor> Descriptors {
		get;
	} = Build();

	/// <summary>名前から記述子を取得（大文字小文字無視）。</summary>
	public static MediaItemPropertyDescriptor? Find(string name) {
		return Descriptors.FirstOrDefault(d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase));
	}

	private static IReadOnlyList<MediaItemPropertyDescriptor> Build() {
		return [
			Comparable<int>("Rate", m => m.Rate),
			Comparable<int>("Width", m => m.Width),
			Comparable<int>("Height", m => m.Height),
			Comparable<int>("UsageCount", m => m.UsageCount),
			Comparable<long>("FileSize", m => m.FileSize),
			Comparable<DateTime>("CreationTime", m => m.CreationTime),
			Comparable<DateTime>("ModifiedTime", m => m.ModifiedTime),
			Comparable<DateTime>("LastAccessTime", m => m.LastAccessTime),
			Comparable<DateTime>("RegisteredTime", m => m.RegisteredTime),
			EnumEqual<MediaType>("MediaType", m => m.MediaType),
			BoolEqual("IsExists", m => m.IsExists),
			BoolEqual("IsInvalid", m => m.IsInvalid),
			BoolEqual("IsAutoGeneratedThumbnail", m => m.IsAutoGeneratedThumbnail),
			BoolEqual("IsUnderFolderGroup", m => m.IsUnderFolderGroup),
			StringEqual("Description", m => m.Description),
			StringEqual("DirectoryPath", m => m.DirectoryPath),
			StringEqual("FilePath", m => m.FilePath),
		];
	}

	private static MediaItemPropertyDescriptor Comparable<T>(string name, Expression<Func<MediaItem, T>> selector)
		where T : struct, IComparable<T>, IParsable<T> {
		return new MediaItemPropertyDescriptor(name, typeof(T), AllComparisons, (op, raw) => {
			if (!T.TryParse(raw, CultureInfo.InvariantCulture, out var v)) {
				return null;
			}
			return SearchTypeConverters.BuildComparisonExpression<MediaItem, T>(op, selector, v);
		});
	}

	private static MediaItemPropertyDescriptor EnumEqual<TEnum>(string name, Expression<Func<MediaItem, TEnum>> selector)
		where TEnum : struct, Enum {
		return new MediaItemPropertyDescriptor(name, typeof(TEnum), EqualityOnly, (op, raw) => {
			if (!Enum.TryParse<TEnum>(raw, true, out var v)) {
				return null;
			}
			return SearchTypeConverters.BuildComparisonExpression<MediaItem, TEnum>(SearchTypeComparison.Equal, selector, v);
		});
	}

	private static MediaItemPropertyDescriptor BoolEqual(string name, Expression<Func<MediaItem, bool>> selector) {
		return new MediaItemPropertyDescriptor(name, typeof(bool), EqualityOnly, (op, raw) => {
			if (!bool.TryParse(raw, out var v)) {
				return null;
			}
			return SearchTypeConverters.BuildComparisonExpression<MediaItem, bool>(SearchTypeComparison.Equal, selector, v);
		});
	}

	private static MediaItemPropertyDescriptor StringEqual(string name, Expression<Func<MediaItem, string>> selector) {
		return new MediaItemPropertyDescriptor(name, typeof(string), EqualityOnly, (op, raw) => {
			return SearchTypeConverters.BuildComparisonExpression<MediaItem, string>(SearchTypeComparison.Equal, selector, raw);
		});
	}
}