using System.IO;
using System.Threading.Tasks;
using MediaDeck.Composition.Enum;
using MediaDeck.Database;
using MediaDeck.Database.Tables;
using MediaDeck.Database.Tables.Metadata;
using MediaDeck.MediaItemTypes.Base.Models;

namespace MediaDeck.MediaItemTypes.FolderGroup.Models;

[Inject(InjectServiceLifetime.Transient)]
internal partial class FolderGroupMediaItemOperator : BaseMediaItemOperator {
	public FolderGroupMediaItemOperator(
		IDbContextFactory<MediaDeckDbContext> dbFactory,
		IFileHashUpdatorService updateFileHashBackgroundService)
		: base(dbFactory, updateFileHashBackgroundService, MediaType.FolderGroup) { }

	public override async Task<MediaItem?> RegisterMediaItemAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();

		var directoryInfo = new DirectoryInfo(filePath);
		var now = DateTime.Now;
		var existing = await db.MediaItems
			.Include(x => x.FolderGroupMetadata)
			.FirstOrDefaultAsync(x => x.FilePath == filePath);

		if (existing is { } existingItem) {
			existingItem.ItemType = ItemType.FolderGroup;
			existingItem.DirectoryPath = directoryInfo.Parent?.FullName ?? filePath;
			existingItem.IsExists = directoryInfo.Exists;
			existingItem.ModifiedTime = directoryInfo.Exists ? directoryInfo.LastWriteTime : existingItem.ModifiedTime;
			existingItem.LastAccessTime = directoryInfo.Exists ? directoryInfo.LastAccessTime : existingItem.LastAccessTime;

			if (existingItem.FolderGroupMetadata is null) {
				existingItem.FolderGroupMetadata = new FolderGroupMetadata();
			}

			db.MediaItems.Update(existingItem);
			await db.SaveChangesAsync();
			await transaction.CommitAsync();
			return null;
		}

		var mediaItem = new MediaItem {
			ItemType = ItemType.FolderGroup,
			DirectoryPath = directoryInfo.Parent?.FullName ?? filePath,
			FilePath = filePath,
			ThumbnailFileName = null,
			Rate = -1,
			Description = string.Empty,
			IsAutoGeneratedThumbnail = false,
			FileSize = 0,
			CreationTime = directoryInfo.Exists ? directoryInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = directoryInfo.Exists ? directoryInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = directoryInfo.Exists ? directoryInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = now,
			IsExists = directoryInfo.Exists,
			FolderGroupMetadata = new FolderGroupMetadata()
		};

		await db.MediaItems.AddAsync(mediaItem);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		return mediaItem;
	}
}