using MediaDeck.Database.Tables;

using System.IO;

using ImageMagick;

using MediaDeck.FileTypes.Base.Models;

using System.Threading.Tasks;

using MediaDeck.Composition.Enum;
using MediaDeck.Composition.Interfaces.FileTypes.Models;
using MediaDeck.FileTypes.Image.Utils;
using MediaDeck.FileTypes.Image.Utils.Formats;

namespace MediaDeck.FileTypes.Image.Models;

[Inject(InjectServiceLifetime.Transient)]
internal class ImageFileOperator : BaseFileOperator {
	private readonly IFilePathService _filePathService;

	public ImageFileOperator(IFilePathService filePathService): base(MediaType.Image) {
		this._filePathService = filePathService;
	}

	public override async Task<MediaFile?> RegisterFileAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaFiles.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}
		using var fileMs = new MemoryStream();

		using (var fileFs = File.OpenRead(filePath)) {
			fileFs.CopyTo(fileMs);
			fileMs.Position = 0;
		}
		var thumbRelativePath = this._filePathService.GetThumbnailRelativeFilePath(filePath);
		var thumbPath = this._filePathService.GetThumbnailAbsoluteFilePath(thumbRelativePath);
		try {
			var image = this.CreateThumbnail(fileMs, 300, 300);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch {
			thumbPath = null;
			thumbRelativePath = null;
		}

		var fileInfo = new FileInfo(filePath);

		var mf = new MediaFile {
			DirectoryPath = Path.GetDirectoryName(filePath)!,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = "",
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists
		};

		// metadata
		fileMs.Position = 0;
		using var meta = ImageMetadataFactory.Create(fileMs);

		if (meta.Latitude != null && meta.Longitude != null && meta.LatitudeRef != null && meta.LongitudeRef != null) {
			var latitude = (meta.Latitude[0].ToDouble() + (meta.Latitude[1].ToDouble() / 60) + (meta.Latitude[2].ToDouble() / 3600)) * (meta.LatitudeRef == "S" ? -1 : 1);
			var longitude = (meta.Longitude[0].ToDouble() + (meta.Longitude[1].ToDouble() / 60) + (meta.Longitude[2].ToDouble() / 3600)) * (meta.LongitudeRef == "W" ? -1 : 1);
			mf.Altitude = meta.Altitude?.ToDouble() * (meta.AltitudeRef == 1 ? -1 : 1);
			mf.Latitude = latitude;
			mf.Longitude = longitude;
			if (!db.Positions.Any(x => x.Latitude == latitude && x.Longitude == longitude)) {
				db.Add(new Position() { Latitude = latitude, Longitude = longitude });
			}
		}

		mf.Height = meta.Height;
		mf.Width = meta.Width;

		if (meta is Jpeg jpeg) {
			mf.Jpeg = jpeg.CreateMetadataRecord();
		} else if (meta is Png png) {
			mf.Png = png.CreateMetadataRecord();
		} else if (meta is Bmp bmp) {
			mf.Bmp = bmp.CreateMetadataRecord();
		} else if (meta is Gif gif) {
			mf.Gif = gif.CreateMetadataRecord();
		} else if (meta is Heif heif) {
			mf.Heif = heif.CreateMetadataRecord();
		}

		await db.MediaFiles.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._updateFileHashBackgroundService.EnqueueHashUpdate(mf.MediaFileId);

		return mf;
	}

	internal byte[] CreateThumbnail(IFileModel fileModel, uint width, uint height) {
		using var fileFs = File.OpenRead(fileModel.FilePath);
		using var ms = new MemoryStream();
		using var mi = new MagickImage(fileFs);
		mi.AutoOrient();
		mi.Thumbnail(width, height);
		mi.Format = MagickFormat.Jpg;
		mi.Write(ms);
		return ms.ToArray();
	}

	internal byte[] CreateThumbnail(Stream fileStream, uint width, uint height) {
		using var ms = new MemoryStream();
		using var mi = new MagickImage(fileStream);
		mi.AutoOrient();
		mi.Thumbnail(width, height);
		mi.Format = MagickFormat.Jpg;
		mi.Write(ms);
		return ms.ToArray();
	}
}