using MediaDeck.Database.Tables;
using System.IO;
using Patagames.Pdf.Net;
using Patagames.Pdf.Enums;
using System.Drawing.Imaging;
using MediaDeck.FileTypes.Base.Models;
using System.Threading.Tasks;
using MediaDeck.Composition.Enum;

namespace MediaDeck.FileTypes.Pdf.Models;
[Inject(InjectServiceLifetime.Transient)]
public partial class PdfFileOperator : BaseFileOperator {

	public override MediaType TargetMediaType {
		get;
	} = MediaType.Pdf;

	public override async Task<MediaFile?> RegisterFileAsync(string filePath) {
		await using var db = await this._dbFactory.CreateDbContextAsync();
		using var transaction = await db.Database.BeginTransactionAsync();
		var isExists = await db.MediaFiles.AnyAsync(x => x.FilePath == filePath);
		if (isExists) {
			return null;
		}

		var thumbRelativePath = FilePathUtility.GetThumbnailRelativeFilePath(filePath);
		var thumbPath = FilePathUtility.GetThumbnailAbsoluteFilePath(thumbRelativePath);
		try {
			var image = this.CreateThumbnail(filePath, 300, 300, 1);
			new FileInfo(thumbPath).Directory?.Create();
			File.WriteAllBytes(thumbPath, image);
		} catch (Exception) {
			thumbPath = null;
			thumbRelativePath = null;
		}

		var pdfDocument = PdfDocument.Load(filePath);
		var fileInfo = new FileInfo(filePath);

		var mf = new MediaFile {
			DirectoryPath = Path.GetDirectoryName(filePath)!,
			FilePath = filePath,
			ThumbnailFileName = thumbRelativePath,
			Rate = -1,
			Description = "",
			IsAutoGeneratedThumbnail = true,
			FileSize = fileInfo.Exists ? fileInfo.Length : 0,
			CreationTime = fileInfo.Exists ? fileInfo.CreationTime : DateTime.MinValue,
			ModifiedTime = fileInfo.Exists ? fileInfo.LastWriteTime : DateTime.MinValue,
			LastAccessTime = fileInfo.Exists ? fileInfo.LastAccessTime : DateTime.MinValue,
			RegisteredTime = DateTime.Now,
			IsExists = fileInfo.Exists,
			Width = (int)pdfDocument.Pages[0].Width,
			Height = (int)pdfDocument.Pages[1].Height,
			Container = new() {
				PageCount = pdfDocument.Pages.Count
			}
		};

		await db.MediaFiles.AddAsync(mf);
		await db.SaveChangesAsync();
		await transaction.CommitAsync();

		this._fileHashUpdater.EnqueueHashUpdate(mf.MediaFileId);

		return mf;
	}

	/// <summary>
	/// サムネイル作成
	/// </summary>
	/// <param name="filePath">動画ファイルパス</param>
	/// <param name="width">サムネイル幅</param>
	/// <param name="height">サムネイル高さ</param>
	/// <param name="pageNumber">サムネイルにするページ番号</param>
	/// <returns>作成されたサムネイルファイル名</returns>
	public byte[] CreateThumbnail(string filePath, int width, int height, int pageNumber = 1) {

		var pdfDoc = PdfDocument.Load(filePath);
		var page = pdfDoc.Pages[pageNumber - 1];
		using var pdfBitmap = new PdfBitmap(width, height, true);
		page.Render(pdfBitmap, 0, 0, width, height, PageRotate.Normal, RenderFlags.FPDF_NONE);
		using var ms = new MemoryStream();

		pdfBitmap.GetImage().Save(ms, ImageFormat.Jpeg);
		return ms.ToArray();
	}
}
